output_dir = "/root/diffusion-pipe/wan-lora"
dataset = "/root/config/dataset_wan.toml"
epochs = 10
micro_batch_size_per_gpu = 2
pipeline_stages = 1
gradient_accumulation_steps = 2
gradient_clipping = 1.0
warmup_steps = 40
eval_every_n_epochs = 1
eval_before_first_step = true
eval_micro_batch_size_per_gpu = 1
eval_gradient_accumulation_steps = 1
save_every_n_epochs = 2
activation_checkpointing = true
partition_method = "parameters"
save_dtype = "bfloat16"
caching_batch_size = 2
steps_per_print = 1
video_clip_mode = "single_beginning"
checkpoint_every_n_epochs = 5

[model]
type = "wan"
ckpt_path = "/root/diffusion-pipe/ckpts/Wan2.1-I2V-14B-480P"
dtype = "bfloat16"
timestep_sample_method = "logit_normal"

[adapter]
type = "lora"
rank = 32
dtype = "bfloat16"

[optimizer]
type = "adamw_optimi"
lr = 0.0001
betas = [ 0.9, 0.99,]
weight_decay = 0.01
eps = 1e-8
